bukkitconsole:
 guiconsole: 
  enabled: true
 serverconsole:
  enabled: true
  password: swordfish
  port: 44444
  maxconnections: 10
 staticserve:
  rootdir: "C:/Users/scyth/workspace/WSHttpServerExample/htdocs"
  saticdir: "C:/Users/scyth/workspace/WSHttpServerExample/htdocs/static"